### ISSUE TITLE
Members nav item selection is very odd

### ISSUE THREAD

**Issue by tavishjain** [UdacityAndroidDevScholarship/gis-2k18#47]
Profile Activity opens up automatically. What I understand is that the profile activity must open when we click on a particular name . 

Also the back button in the profile activity (toolbar) doesn't do anything . 

On swiping up in the profile activity, there is a large gap between the toolbar and the tabs , that looks really  bad

**Comment by TheRaider** [comment]
@tavishjain The code for it is added and a PR is also made.

**Comment by TheRaider** [comment]
@tavishjain The PR of starter code of Members section is merged and some of the issues you have mentioned are still there. Fetch the master branch now and point out all bugs and issues you want to resolve and post the list of bugs/issues here in form of bullet points so that we can assign the issue to you
