### ISSUE TITLE
Project UI Mock UP Section 

### ISSUE THREAD

**Issue by Rahulxx01** [UdacityAndroidDevScholarship/gis-2k18#5]
**Project Section Activity**

This activity will consist of all the **list of collaborative projects explained briefly** and also a **link** will be provided for **contributions**.

This activity will also consist of all the projects discussed by the students in the **#shareIdeas** channel and some description will be provided so that future students interested will be encouraged to collaborate.

_**You can share and submit all your mocks ups related to Project section here**_

**Our main aim is for a User-friendly UI**

For eg:
![projects](https://user-images.githubusercontent.com/24786147/38680067-06fda94c-3e83-11e8-92c3-aeaac051b4bc.png)

**We open for suggestion for improvement and even better UI mockup** 

P.S: Please resize the image if it's too big.
[Click here to know how to do it.](https://github.com/UdacityAndroidDevScholarship/gis-2k18/wiki/Usefull-markdown-things-will-posting-issues-and-PRs)

**Comment by surya07081995** [comment]
Hi Mods,
As per your requirement, I have  designed UI for the project section activity,
I'm uploading the desktop view, as due to some problem unable to generate the link. 
Do consider the UI if it looks good to you.

Snapshot 1:
GIS 2k18(Flip to read)

![gis](https://user-images.githubusercontent.com/20954321/38876317-dd45208a-4279-11e8-979f-2091bc1a4ee0.jpg)

Snapshot 2:
Explore India(Flip to read)

![explore](https://user-images.githubusercontent.com/20954321/38876470-27f97266-427a-11e8-9e3f-b68a9d4fe585.jpg)

Snapshot 3:
Blood Donation(Flip to read)

![blood](https://user-images.githubusercontent.com/20954321/38876579-5b108c5c-427a-11e8-8ddb-2feb9135817a.jpg)

Snapshot 4:
Quiz app(Flip to read)

![quiz](https://user-images.githubusercontent.com/20954321/38876651-854acfb4-427a-11e8-87a0-0f63975a1105.jpg)

if image gets blur then do check desktop view
Link to Desktop view: https://drive.google.com/open?id=1WB0awSpqB5SVIoQaQHuGGmioPGwuCeuX

Your thoughts and suggestions are highly appreciated.
Thanks!

**Comment by surya07081995** [comment]
Sure @Saurav2304, I will submittimg XML file of above UI soon.
